### ISSUE TITLE
read_task is none

### ISSUE THREAD

**Issue by rrashton** [pgiri/pycos#1]
When queued io task returns CONNECTION_INVALID or OPERATION_ABORTED, self._read_task is None, and _proceed throws an exception.
I've solved it locally by adding the following to _recvall in ___init___.py, line 1435 -

           
                            if (err == winerror.ERROR_CONNECTION_INVALID or
                            err == winerror.ERROR_OPERATION_ABORTED):

                                if self._read_task is None:
                                    self._read_task = Pycos.cur_task(self._scheduler)
                                if self._read_task is not None:
                                    self._read_task._proceed_('')

Instead of 
`               
                         if (err == winerror.ERROR_CONNECTION_INVALID or
                        err == winerror.ERROR_OPERATION_ABORTED):
                            self._read_task._proceed_('')`

**Comment by pgiri** [comment]
Thanks for reporting it.

Can you attach a sample program that throws the exception? If it is not possible, can you describe what caused it? For example, did it happen when the program is exiting? Or, is it possible same socket is read in two different tasks? I can see this issue in those cases, but otherwise, it is not supposed to happen (that is, socket's `_read_task` being set to `None` while recv is not complete.

The fix you propose may not work in all cases; e.g., `cur_task` may not be the task from which recv was initiated. If you need to avoid exception, I suggest:

                       if (err == winerror.ERROR_CONNECTION_INVALID or
                        err == winerror.ERROR_OPERATION_ABORTED):
                            if self._read_task:
                                self._read_task._proceed_('')
                            else:
                                logger.warning('Invalid recv error %s ignored', err)

This will not cause another (unrelated) task to receive data (empty buffer).

**Comment by rrashton** [comment]
Hi, thanks for the reply.
The exception took a while to reproduce, it happened when using dispy for a long time, with many jobs that include file transfers. I think that it happens in case of dispy cluster being shutdown or disconnected.
Your fix looks good, I will try to change that in my code.
Thanks !

**Comment by pgiri** [comment]
Could you try above commit? I think this issue is not (easily) reproducible, as it is a bit non-deterministic and occurs when shutting down.

**Comment by rrashton** [comment]
Sorry for the late reply,
it works!! thanks
